### ISSUE TITLE
weather.ou.edu/~apw/projects/stress/ 403 forbidden

### ISSUE THREAD

**Issue by grahamperrin** [cooljeanius/stress-1.0.4#2]
https://github.com/cooljeanius/stress-1.0.4/blob/dcbbb91abcf04c9c1f0d712a9208ef162e1f2dde/README.md?plain=1#L25

@cooljeanius FYI http://weather.ou.edu/~apw/projects/stress/ is: 

> Forbidden
> 
> You don't have permission to access /~apw/projects/stress/ on this server.

@ColinIanKing please, might you suggest an alternative point of reference?

Thanks

Cross reference: [Best primary point of reference for sysutils/stress | The FreeBSD Forums](https://forums.freebsd.org/threads/best-primary-point-of-reference-for-sysutils-stress.81874/)

**Comment by cooljeanius** [comment]
oops, let me find an archive link...

**Comment by grahamperrin** [comment]
<https://web.archive.org/web/0/http://weather.ou.edu/~apw/projects/stress/> 

* captures began in 2002
* May 2013 <https://web.archive.org/web/20130520190152/http://weather.ou.edu/~apw/projects/stress/>
* June 2013 `404`, _The requested URL /~apw/projects/stress/ was not found on this server._

<https://web.archive.org/web/20190707055144/http://people.seas.harvard.edu:80/~apw/stress/> (July 2019) was found automatically by the [Wayback Machine](https://addons.mozilla.org/addon/wayback-machine_new/) extension for Firefox (and given at <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258099#c0>); the earliest capture was 23rd November 2013.

**Comment by cooljeanius** [comment]
should be fixed by 2810e98

**Comment by cooljeanius** [comment]
I tried updating my local MacPorts Portfile for this package to use the archive link in cooljeanius/LocalPorts@555348d, but unfortunately that results in it trying to download an empty tarball...

**Comment by grahamperrin** [comment]
> trying to download an empty tarball

Try https://cgit.freebsd.org/ports/commit/sysutils/stress/Makefile?id=4f3347409019bce428669e06180e643e66feb7ee

**Comment by cooljeanius** [comment]
> > trying to download an empty tarball
> 
> Try https://cgit.freebsd.org/ports/commit/sysutils/stress/Makefile?id=4f3347409019bce428669e06180e643e66feb7ee

OK, I did that in cooljeanius/LocalPorts@6f35e07; thanks!

**Comment by ColinIanKing** [comment]
On 27/08/2021 23:23, Graham Perrin wrote:
> https://github.com/cooljeanius/stress-1.0.4/blob/dcbbb91abcf04c9c1f0d712a9208ef162e1f2dde/README.md?plain=1#L25
> <https://github.com/cooljeanius/stress-1.0.4/blob/dcbbb91abcf04c9c1f0d712a9208ef162e1f2dde/README.md?plain=1#L25>
> 
> @cooljeanius <https://github.com/cooljeanius> FYI
> http://weather.ou.edu/~apw/projects/stress/
> <http://weather.ou.edu/~apw/projects/stress/> is:
> 
>     Forbidden
> 
>     You don't have permission to access /~apw/projects/stress/ on this
>     server.
> 
> @ColinIanKing <https://github.com/ColinIanKing> please, might you
> suggest an alternative point of reference?

Afraid not. I can't find it either.

Colin

**Comment by grahamperrin** [comment]
@cooljeanius: thanks again. 

@ColinIanKing: thanks; <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258099#c2> I reckon that a Wayback Machine capture will be better than hothing.
